// Generated by LiveScript 1.6.0
(function(){
  var express, cors, expressRateLimit, proxy, create, limitConfig, limiter, app;
  express = require('express');
  cors = require('cors');
  expressRateLimit = require('express-rate-limit');
  proxy = require('express-http-proxy');
  create = require('greenlock-express').create;
  limitConfig = {
    windowMs: 150 * 60 * 1000,
    max: 10000
  };
  limiter = expressRateLimit(limitConfig);
  app = express().use(limiter).use(cors()).use('/api', proxy("http://localhost:8545")).use('/', express['static']('./'));
  app.listen(80);
}).call(this);
