// Generated by LiveScript 1.5.0
(function(){
  var express, cors, web3, createModule, balance, txlist, account, contract, transaction, block, logs, proxy, stats, modules, api, responsity, app;
  express = require('express');
  cors = require('cors');
  web3 = require('./web3.js');
  createModule = function(actions){
    return function(query, cb){
      var action;
      action = actions[query.action];
      if (action == null) {
        return cb('Action Not Found');
      }
      return action(query, cb);
    };
  };
  balance = function(query, cb){
    if (query.address == null) {
      return cb("Address is required");
    }
    return web3.eth.getBalance(query.address, function(err, data){
      if (err != null) {
        return cb(err);
      }
      return cb(null, data.toString());
    });
  };
  txlist = function(query, cb){
    return cb(null, []);
  };
  account = createModule({
    balance: balance,
    txlist: txlist
  });
  contract = createModule({});
  transaction = createModule({});
  block = createModule({});
  logs = createModule({});
  proxy = createModule({});
  stats = createModule({});
  modules = {
    account: account,
    contract: contract,
    transaction: transaction,
    block: block,
    logs: logs,
    proxy: proxy,
    stats: stats
  };
  api = function(query, cb){
    var module;
    console.log(JSON.stringify(query));
    module = modules[query.module];
    if (module == null) {
      return cb('Module Not Found');
    }
    return module(query, function(err, data){
      if (err != null) {
        return cb(err);
      }
      return cb(null, data);
    });
  };
  responsity = function(res){
    return function(err, result){
      var ref$;
      if (err != null) {
        return res.send({
          status: "0",
          message: "ERROR",
          result: (ref$ = err.message) != null ? ref$ : err
        });
      }
      return res.send({
        status: "1",
        message: "OK",
        result: result
      });
    };
  };
  app = express().use(cors()).use(express['static']('app')).get('/api', function(req, res){
    return api(req.query, responsity(res));
  }).get('/*', function(req, res){
    return res.redirect("/#" + req.url);
  });
  app.listen(8000, function(){
    return console.log('Example app listening on port 8000!');
  });
}).call(this);
