// Generated by LiveScript 1.5.0
(function(){
  var express, createModule, balance, account, contract, transaction, block, logs, proxy, stats, modules, app;
  express = require('express');
  createModule = function(actions){
    return function(query, cb){
      var action;
      action = actions[query.action];
      if (action == null) {
        return cb('Action Not Found');
      }
      return action(query, cb);
    };
  };
  balance = function(query, cb){
    return cb("Not Implemented");
  };
  account = createModule({
    balance: balance
  });
  contract = createModule({});
  transaction = createModule({});
  block = createModule({});
  logs = createModule({});
  proxy = createModule({});
  stats = createModule({});
  modules = {
    account: account,
    contract: contract,
    transaction: transaction,
    block: block,
    logs: logs,
    proxy: proxy,
    stats: stats
  };
  app = express().use(express['static']('app')).get('/api', function(req, res){
    var module;
    module = modules[req.query.module];
    if (module == null) {
      res.status(404).send('Module Not Found');
    }
    return module(req.query, function(err, data){
      var ref$;
      if (err == null) {
        res.status(500).send((ref$ = err.message) != null ? ref$ : err);
      }
      return res.send(data);
    });
  }).get('/*', function(req, res){
    return res.redirect("/#" + req.url);
  });
  app.listen(8000, function(){
    return console.log('Example app listening on port 8000!');
  });
}).call(this);
