// Generated by LiveScript 1.5.0
(function(){
  var rpcUrl, Web3, web3;
  rpcUrl = require('./app/config.json').rpcUrl;
  Web3 = require('web3');
  web3 = new Web3;
  web3.setProvider(new web3.providers.HttpProvider(rpcUrl));
  module.exports = web3;
}).call(this);
